### ISSUE TITLE
Looking to try out the project but the download link is really slow

### ISSUE THREAD

**Issue by hasnainv** [r00tman/NeRF-OSR#1]
Hi there,

This is a very promising project, thanks for open-sourcing it.
We are trying to evaluate the project, but the model and data download link is really slow (< 100 kbps).
In the best interest of the project, can the data and models please be uploaded to some other cloud storage?

Thanks

**Comment by r00tman** [comment]
Hi, thank you for your feedback and sorry for the delay.

I guess the speed could have been slow due how many people were trying to download the data at the same time.
If it is still the problem, please write here, we'll look into it.
