### ISSUE TITLE
Question about min_depth and max_depth in your code and data

### ISSUE THREAD

**Issue by LinZhuoChen** [r00tman/NeRF-OSR#2]
Hi~ Thanks for your awesome work!
I am using your dataset to train my own nerf. I see min_depth and max_depth in your dataloder. But I have not seen these in your provided dataset. Are min_depth and max_depth nesseary? Will it cause error in your code when min_depth is None?

Hope for your reply, Thank you very much.

**Comment by r00tman** [comment]
Hi, thank you!
Sorry for the late reply.
Yes, we did not use min_depth or max_depth at all, they were set to None for all of the experiments.
