### ISSUE TITLE
Weird Parameters?

### ISSUE THREAD

**Issue by MikePelton** [r00tman/NeRF-OSR#3]
Hi Viktor et al - very excited about this code, but in all the test*.sh files there's a parameter --test_env e.g.:
python ddp_test_nerf.py --config configs/europa/final.txt --render_splits static_path1_blend --test_env data/europa/final/static_path1_blend/envmaps
...but "--test-env" doesn't seem to be a supported parameter - I can't see it added anywhere in the code, and ddp_test_nerf.py never gets past the fact it doesn't recognise one or more parameters. Am I missing something obvious?

**Comment by r00tman** [comment]
Hi, thank you! Sorry for the delay. 

Yes, good catch. I think I initally uploaded the version where it was not yet there. The parameter should have controlled which lighting should be used for rendering. Specifically, the missing code starting from [here](https://github.com/r00tman/NeRF-OSR/blob/main/ddp_model.py#L378) should replace `env` with the lighting from the provided folder.

I just uploaded the correct version, which implements `--test_env`.
If there is any problem, please write here.

**Comment by MikePelton** [comment]
Brilliant - many thanks!
